In [1]:
import pandas as pd

clinical_data = pd.read_csv("../genomic/tcga_cbio/clinical_data.csv", sep='\t', dtype=object)
mutation_data = pd.read_csv("../genomic/tcga_cbio/mutation_data.csv", sep='\t', dtype=object)

In [2]:
group_variants = mutation_data.groupby('START_POSITION')
sr = group_variants.apply(lambda x: len(x['PATIENT_ID'].unique()))
#nbr_patients_per_variant
nppv = pd.DataFrame({'START_POSITION':sr.index, 'count':sr.values})

In [3]:
df_position = nppv.loc[nppv['count']==15]
pos = df_position.iloc[0]['START_POSITION']

df = mutation_data.loc[mutation_data['START_POSITION']==pos]

In [4]:
data_query = df.head(1)
patient_ids = df['PATIENT_ID']
for _, val in patient_ids.iteritems():
    tmp = (mutation_data.loc[mutation_data['PATIENT_ID']==val]).head(1)
    data_query = data_query.append(tmp)
    
other_variants = mutation_data.head(200-16)
data_query = data_query.append(other_variants)

export_csv = data_query.to_csv(r'query.csv', index = None, header=True) #Don't forget to add '.csv' at the end of the path
data_query

,CANCER_STUDY_ID,CANCER_STUDY_IDENTIFIER,PATIENT_ID,SAMPLE_ID,TUMOR_SEQ_ALLELE1,TUMOR_SEQ_ALLELE2,TUMOR_ALT_COUNT,TUMOR_REF_COUNT,NORMAL_ALT_COUNT,NORMAL_REF_COUNT,...,START_POSITION,END_POSITION,REFERENCE_ALLELE,PROTEIN_CHANGE,MUTATION_TYPE,NCBI_BUILD,STRAND,VARIANT_TYPE,ENTREZ_GENE_ID,HUGO_GENE_SYMBOL
75069,191,brca_tcga,45956,47433,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
75049,191,brca_tcga,45956,47433,A,-,-1,-1,-1,-1,...,56336954,56336954,A,L123*,Frame_Shift_Del,GRCh37,-1,DEL,9575,CLOCK
216986,199,esca_tcga,48143,49628,G,A,-1,-1,-1,-1,...,105464438,105464438,G,P113L,Missense_Mutation,GRCh37,-1,SNP,160428,ALDH1L2
241795,199,esca_tcga,48263,49748,G,-,-1,-1,-1,-1,...,98211549,98211549,G,S1203Afs*52,Frame_Shift_Del,GRCh37,-1,DEL,5727,PTCH1
828991,216,stad_tcga,64661,66667,-,GGGGCGCAGCAGCTG,-1,-1,-1,-1,...,46012219,46012220,NaN,P49_A50insSCCAP,In_Frame_Ins,GRCh37,-1,INS,386674,KRTAP10-6
842191,216,stad_tcga,64714,66720,-,TCA,-1,-1,-1,-1,...,48777220,48777221,NaN,D106dup,In_Frame_Ins,GRCh37,-1,INS,91369,ANKRD40
852667,216,stad_tcga,64742,66748,G,A,-1,-1,-1,-1,...,161495078,161495078,G,V25M,Missense_Mutation,GRCh37,1,SNP,2566,GABRG2
855638,216,stad_tcga,64751,66757,GCT,-,-1,-1,-1,-1,...,39261568,39261570,GCT,L38del,In_Frame_Del,GRCh37,1,DEL,341640,FREM2
867766,216,stad_tcga,64797,66803,C,T,-1,-1,-1,-1,...,11676525,11676525,C,W85*,Nonsense_Mutation,GRCh37,-1,SNP,221981,THSD7A
879770,216,stad_tcga,64826,66832,G,A,-1,-1,-1,-1,...,7577121,7577121,G,R273C,Missense_Mutation,GRCh37,-1,SNP,7157,TP53
905110,216,stad_tcga,64882,66888,A,-,-1,-1,-1,-1,...,9989571,9989571,A,N66Tfs*26,Frame_Shift_Del,GRCh37,1,DEL,9014,TAF1B
911138,216,stad_tcga,64897,66903,C,T,-1,-1,-1,-1,...,37027834,37027834,C,R451C,Missense_Mutation,GRCh37,1,SNP,442444,FAM47C
918774,216,stad_tcga,64947,66953,C,T,-1,-1,-1,-1,...,7578406,7578406,C,R175H,Missense_Mutation,GRCh37,-1,SNP,7157,TP53
940340,216,stad_tcga,65069,67075,T,-,-1,-1,-1,-1,...,6012690,6012690,T,N973Mfs*12,Frame_Shift_Del,GRCh37,-1,DEL,26953,RANBP6
944048,216,stad_tcga,65075,67081,C,T,-1,-1,-1,-1,...,37868208,37868208,C,S310F,Missense_Mutation,GRCh37,1,SNP,2064,ERBB2
964621,216,stad_tcga,65125,67131,C,T,-1,-1,-1,-1,...,43926756,43926756,C,R1441H,Missense_Mutation,GRCh37,-1,SNP,64800,EFCAB6
0,185,acc_tcga,42261,43717,GCTGTGGCTCCAGCTCTGGGGGAA,-,22,83,0,105,...,152785074,152785097,GCTGTGGCTCCAGCTCTGGGGGAA,S59_G66del,In_Frame_Del,GRCh37,1,DEL,353132,LCE1B
1,185,acc_tcga,42261,43717,A,C,5,60,1,117,...,53298675,53298675,A,S31A,Missense_Mutation,GRCh37,-1,SNP,3856,KRT8
2,185,acc_tcga,42261,43717,-,T,8,18,0,57,...,80274159,80274160,-,A175Dfs*40,Frame_Shift_Ins,GRCh37,-1,INS,924,CD7
3,185,acc_tcga,42261,43717,G,-,7,16,0,50,...,80274162,80274162,G,P174Qfs*12,Frame_Shift_Del,GRCh37,-1,DEL,924,CD7
4,185,acc_tcga,42261,43717,C,T,27,4,0,52,...,101409174,101409174,C,A22T,Missense_Mutation,GRCh37,-1,SNP,340542,BEX5
5,185,acc_tcga,42261,43717,G,A,82,96,0,142,...,136973018,136973018,G,T429M,Missense_Mutation,GRCh37,-1,SNP,26249,KLHL3
6,185,acc_tcga,42261,43717,C,T,4,47,0,51,...,35696518,35696518,C,R121H,Missense_Mutation,GRCh37,-1,SNP,5933,RBL1
7,185,acc_tcga,42261,43717,C,G,51,77,0,111,...,26031919,26031919,C,D124H,Missense_Mutation,37,NaN,SNP,8358,HIST1H3B
8,185,acc_tcga,42261,43717,C,A,6,69,0,61,...,173499091,173499091,C,A756S,Missense_Mutation,GRCh37,+,SNP,284525,SLC9C2
9,185,acc_tcga,42261,43717,T,G,5,154,0,109,...,225569241,225569241,T,F3236C,Missense_Mutation,GRCh37,+,SNP,127602,DNAH14
10,185,acc_tcga,42261,43717,G,A,12,162,0,163,...,88419681,88419681,G,G277D,Missense_Mutation,GRCh37,+,SNP,94233,OPN4
11,185,acc_tcga,42261,43717,G,T,7,47,0,60,...,64001585,64001585,G,G219W,Missense_Mutation,GRCh37,+,SNP,3338,DNAJC4
12,185,acc_tcga,42261,43717,C,G,127,185,1,213,...,9760409,9760409,C,E9D,Missense_Mutation,GRCh37,+,SNP,3820,KLRB1
13,185,acc_tcga,42261,43717,C,T,53,61,1,89,...,21991730,21991730,C,R711Q,Missense_Mutation,GRCh37,+,SNP,6297,SALL2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,185,acc_tcga,42263,43719,C,T,8,204,3,238,...,182554557,182554557,C,R462Q,Missense_Mutation,GRCh37,+,SNP,6041,RNASEL
155,185,acc_tcga,42263,43719,G,T,6,212,0,99,...,99186071,99186071,G,A3S,Missense_Mutation,GRCh37,+,SNP,5223,PGAM1
156,185,acc_tcga,42263,43719,C,T,61,13,0,98,...,112540915,112540915,C,S183F,Missense_Mutation,GRCh37,+,SNP,282996,RBM20
157,185,acc_tcga,42263,43719,G,A,4,95,0,121,...,48149412,48149412,G,E392K,Missense_Mutation,GRCh37,+,SNP,5795,PTPRJ
158,185,acc_tcga,42263,43719,G,T,3,13,0,35,...,68837957,68837957,G,V297L,Missense_Mutation,GRCh37,+,SNP,219931,TPCN2
159,185,acc_tcga,42263,43719,G,T,119,12,0,145,...,100095508,100095508,G,D657Y,Missense_Mutation,GRCh37,+,SNP,53942,CNTN5
160,185,acc_tcga,42263,43719,T,C,83,199,0,170,...,81777846,81777846,T,K314E,Missense_Mutation,GRCh37,+,SNP,8499,PPFIA2
161,185,acc_tcga,42263,43719,G,A,4,92,0,83,...,124239085,124239085,G,X764_splice,Splice_Site,GRCh37,+,SNP,23545,ATP6V0A2
162,185,acc_tcga,42263,43719,G,T,5,154,0,83,...,68597636,68597636,G,G316W,Missense_Mutation,GRCh37,+,SNP,146198,ZFP90
163,185,acc_tcga,42263,43719,T,C,35,7,0,5,...,39305775,39305775,T,Q82R,Missense_Mutation,GRCh37,+,SNP,85289,KRTAP4-5
164,185,acc_tcga,42263,43719,G,T,4,78,0,114,...,65190106,65190106,G,S178R,Missense_Mutation,GRCh37,+,SNP,9931,HELZ
165,185,acc_tcga,42263,43719,C,-,94,26,2,152,...,66526554,66526554,C,Q371Sfs*70,Frame_Shift_Del,GRCh37,+,DEL,5573,PRKAR1A
166,185,acc_tcga,42263,43719,C,G,35,70,0,12,...,932572,932572,C,R175G,Missense_Mutation,GRCh37,+,SNP,1820,ARID3A
167,185,acc_tcga,42263,43719,T,G,5,45,0,41,...,24307079,24307079,T,N40H,Missense_Mutation,GRCh37,+,SNP,9540,TP53I3
168,185,acc_tcga,42263,43719,G,A,4,33,0,34,...,86400824,86400824,G,P124S,Missense_Mutation,GRCh37,+,SNP,10989,IMMT
169,185,acc_tcga,42263,43719,T,C,11,1,0,2,...,241827798,241827798,T,I388V,Missense_Mutation,GRCh37,+,SNP,79919,C2ORF54
170,185,acc_tcga,42263,43719,G,T,5,40,0,23,...,33762727,33762727,G,R98L,Missense_Mutation,GRCh37,+,SNP,10544,PROCR
171,185,acc_tcga,42263,43719,C,A,3,67,0,32,...,39826114,39826114,C,H468N,Missense_Mutation,GRCh37,+,SNP,10454,TAB1
172,185,acc_tcga,42263,43719,G,C,3,62,0,56,...,47163592,47163592,G,S845*,Nonsense_Mutation,GRCh37,+,SNP,29072,SETD2
173,185,acc_tcga,42263,43719,G,T,11,130,0,72,...,52255624,52255624,G,A903E,Missense_Mutation,GRCh37,+,SNP,54106,TLR9
174,185,acc_tcga,42263,43719,C,T,4,188,0,179,...,150916947,150916947,C,G76D,Missense_Mutation,GRCh37,+,SNP,29909,GPR171
175,185,acc_tcga,42263,43719,T,G,9,35,1,45,...,185797720,185797720,T,H179P,Missense_Mutation,GRCh37,+,SNP,2119,ETV5
176,185,acc_tcga,42263,43719,G,T,77,100,0,117,...,13870993,13870993,G,F1239L,Missense_Mutation,GRCh37,+,SNP,1767,DNAH5
177,185,acc_tcga,42263,43719,GAA,-,7,665,0,466,...,79041149,79041151,GAA,K3617del,In_Frame_Del,GRCh37,+,DEL,202333,CMYA5
178,185,acc_tcga,42263,43719,A,G,4,94,0,60,...,176315851,176315851,A,I310T,Missense_Mutation,GRCh37,+,SNP,3101,HK3
179,185,acc_tcga,42263,43719,A,T,93,15,1,120,...,51920393,51920393,A,Y610N,Missense_Mutation,GRCh37,+,SNP,5314,PKHD1
180,185,acc_tcga,42263,43719,C,A,4,85,0,58,...,8239069,8239069,C,R63S,Missense_Mutation,GRCh37,+,SNP,157285,SGK223
181,185,acc_tcga,42263,43719,G,T,5,200,0,236,...,73850257,73850257,G,L889F,Missense_Mutation,GRCh37,+,SNP,9312,KCNB2
182,185,acc_tcga,42263,43719,C,T,13,1,0,0,...,132052342,132052342,C,A80T,Missense_Mutation,GRCh37,+,SNP,114,ADCY8
183,185,acc_tcga,42263,43719,G,T,5,82,1,60,...,137727048,137727048,G,A1790S,Missense_Mutation,GRCh37,+,SNP,1289,COL5A1

In [5]:
and_query = data_query.head(1)
or_query = data_query.iloc[1:]

sp_and = and_query['START_POSITION']
ep_and = and_query['END_POSITION']
tsa1_and = and_query['TUMOR_SEQ_ALLELE1']
tsa2_and = and_query['TUMOR_SEQ_ALLELE2']

sp = or_query['START_POSITION']
ep = or_query['END_POSITION']
tsa1 = or_query['TUMOR_SEQ_ALLELE1']
tsa2 = or_query['TUMOR_SEQ_ALLELE2']

query_part1 = mutation_data.loc[mutation_data['START_POSITION'].isin(sp) & mutation_data['END_POSITION'].isin(ep) & mutation_data['TUMOR_SEQ_ALLELE1'].isin(tsa1) & mutation_data['TUMOR_SEQ_ALLELE2'].isin(tsa2)]
pIDs = query_part1['PATIENT_ID'].values
patients_query_part1 = clinical_data.loc[clinical_data['PATIENT_ID'].isin(pIDs)]

data2 = mutation_data.loc[mutation_data['PATIENT_ID'].isin(pIDs)]
query_part2 = data2[data2['START_POSITION']==sp_and.values[0]]
query_part2 = query_part2[query_part2['END_POSITION']==ep_and.values[0]]
query_part2 = query_part2[query_part2['TUMOR_SEQ_ALLELE1']==tsa1_and.values[0]]
query_part2 = query_part2[query_part2['TUMOR_SEQ_ALLELE2']==tsa2_and.values[0]]
query_part2

,CANCER_STUDY_ID,CANCER_STUDY_IDENTIFIER,PATIENT_ID,SAMPLE_ID,TUMOR_SEQ_ALLELE1,TUMOR_SEQ_ALLELE2,TUMOR_ALT_COUNT,TUMOR_REF_COUNT,NORMAL_ALT_COUNT,NORMAL_REF_COUNT,...,START_POSITION,END_POSITION,REFERENCE_ALLELE,PROTEIN_CHANGE,MUTATION_TYPE,NCBI_BUILD,STRAND,VARIANT_TYPE,ENTREZ_GENE_ID,HUGO_GENE_SYMBOL
75069,191,brca_tcga,45956,47433,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
217022,199,esca_tcga,48143,49628,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
241826,199,esca_tcga,48263,49748,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
829001,216,stad_tcga,64661,66667,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
842221,216,stad_tcga,64714,66720,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
852686,216,stad_tcga,64742,66748,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
855655,216,stad_tcga,64751,66757,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
867781,216,stad_tcga,64797,66803,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
879788,216,stad_tcga,64826,66832,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
905131,216,stad_tcga,64882,66888,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
911165,216,stad_tcga,64897,66903,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
918838,216,stad_tcga,64947,66953,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
940362,216,stad_tcga,65069,67075,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
944064,216,stad_tcga,65075,67081,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2
964641,216,stad_tcga,65125,67131,A,-,-1,-1,-1,-1,...,102503432,102503432,A,N849Tfs*14,Frame_Shift_Del,GRCh37,1,DEL,2898,GRIK2

In [21]:
short_data = mutation_data.drop(columns=['CANCER_STUDY_ID','CANCER_STUDY_IDENTIFIER','SAMPLE_ID','TUMOR_SEQ_ALLELE1','TUMOR_ALT_COUNT','TUMOR_REF_COUNT','NORMAL_ALT_COUNT','NORMAL_REF_COUNT','PROTEIN_CHANGE','MUTATION_TYPE','NCBI_BUILD','STRAND','VARIANT_TYPE','ENTREZ_GENE_ID','HUGO_GENE_SYMBOL'])
short_data.to_csv(r'mutation_data_small.csv', index = None, header=True) #Don't forget to add '.csv' at the end of the path

NameError: name 'mutation_data' is not defined